#!/bin/sh

set -e

if [ $# -eq 3 ] || [ $# -eq 4 ]; then
	kernelversion="$1"
	bootimage="$2"
	mapfile="$3"
	destdir="${4:-/boot}"
else
	echo "Usage: installkernel <version> <image> <System.map> <directory>"
	exit 1
fi

mapdir=$(dirname "$mapfile")
config="$mapdir"/.config

suffix="$kernelversion"
flavor=${kernelversion##*[0-9]-}

cd "$destdir"
for i in vmlinuz System.map config; do
	if [ -e $i-$suffix ]; then
		cp $i-$suffix $i-$suffix.old
	fi
done
for i in vmlinuz; do
	ln -sf $i-$suffix $i.$flavor
done
cd -

cp "$bootimage" "$destdir"/vmlinuz-${suffix}
cp "$mapfile" "$destdir"/System.map-${suffix}
cp "$config" "$destdir"/config-${suffix}

exit 0
